"""Demo organisation, zones and templates. Zone polygons are rough approximations for development;
production zones come from the CAA (published) and from each agency (sensitive sites, server only)."""

AGENCIES = [
    # code, kind, name, name_zh
    ("NPA", "police", "National Police Agency", "內政部警政署"),
    ("TCPD", "police", "Taipei City Police Department", "臺北市政府警察局"),
    ("NTPD", "police", "New Taipei City Police Department", "新北市政府警察局"),
    ("TYPD", "police", "Taoyuan City Police Department", "桃園市政府警察局"),
    ("TCHPD", "police", "Taichung City Police Department", "臺中市政府警察局"),
    ("KCPD", "police", "Kaohsiung City Police Department", "高雄市政府警察局"),
    ("PHPD", "police", "Penghu County Police Bureau", "澎湖縣政府警察局"),
    ("KMPD", "police", "Kinmen County Police Bureau", "金門縣警察局"),
    ("LCPD", "police", "Lienchiang County Police Bureau", "連江縣警察局"),
    ("APB", "police", "Aviation Police Bureau", "內政部警政署航空警察局"),
    ("CAA", "caa", "Civil Aviation Administration", "交通部民用航空局"),
    ("CGA", "coast_guard", "Coast Guard Administration", "海洋委員會海巡署"),
    ("MND", "defense", "Ministry of National Defense", "國防部"),
]

DESKS = [
    # code, agency, name, name_zh, clearance, catch_all, always_staffed
    ("NPA-CMD", "NPA", "NPA Command Center (national catch-all)", "警政署勤務指揮中心", 1, True, True),
    ("MND-JOC", "MND", "MND Joint Operations Center", "國防部聯合作戰中心", 2, True, True),
    ("TCPD-DISPATCH", "TCPD", "Taipei Police dispatch", "臺北市警察局勤務指揮中心", 1, False, True),
    ("NTPD-DISPATCH", "NTPD", "New Taipei Police dispatch", "新北市警察局勤務指揮中心", 1, False, True),
    ("TYPD-DISPATCH", "TYPD", "Taoyuan Police dispatch", "桃園市警察局勤務指揮中心", 1, False, True),
    ("TCHPD-DISPATCH", "TCHPD", "Taichung Police dispatch", "臺中市警察局勤務指揮中心", 1, False, True),
    ("KCPD-DISPATCH", "KCPD", "Kaohsiung Police dispatch", "高雄市警察局勤務指揮中心", 1, False, True),
    ("PHPD-DISPATCH", "PHPD", "Penghu Police dispatch", "澎湖縣警察局勤務指揮中心", 1, False, True),
    ("KMPD-DISPATCH", "KMPD", "Kinmen Police dispatch", "金門縣警察局勤務指揮中心", 1, False, True),
    ("LCPD-DISPATCH", "LCPD", "Lienchiang Police dispatch", "連江縣警察局勤務指揮中心", 1, False, True),
    ("APB-OPS", "APB", "Aviation Police operations", "航空警察局勤務指揮中心", 1, False, True),
    ("CAA-UAS", "CAA", "CAA drone desk (office hours)", "民航局遙控無人機管理窗口", 0, False, False),
    ("CGA-KINMEN", "CGA", "Coast Guard Kinmen-Matsu-Penghu", "海巡署金馬澎分署", 1, False, True),
    ("MND-KINMEN", "MND", "Kinmen Defense Command ops desk", "金門防衛指揮部作戰中心", 2, False, False),
    ("MND-AIRBASE", "MND", "Air base security desk", "空軍基地安全管制", 2, False, False),
]

# (code, name, name_zh, type, classification, published, priority, shape, primary, backups, ack_timeouts)
# shape: ("circle", lat, lon, radius_m) or ("bbox", south, west, north, east)
ZONES = [
    (
        "JUR-TPE",
        "Taipei City",
        "臺北市",
        "jurisdiction",
        0,
        False,
        10,
        ("bbox", 24.96, 121.457, 25.21, 121.666),
        "TCPD-DISPATCH",
        [],
        {},
    ),
    (
        "JUR-NTPC",
        "New Taipei City",
        "新北市",
        "jurisdiction",
        0,
        False,
        5,
        ("bbox", 24.67, 121.28, 25.30, 122.01),
        "NTPD-DISPATCH",
        [],
        {},
    ),
    (
        "JUR-TYN",
        "Taoyuan City",
        "桃園市",
        "jurisdiction",
        0,
        False,
        6,
        ("bbox", 24.59, 120.98, 25.13, 121.47),
        "TYPD-DISPATCH",
        [],
        {},
    ),
    (
        "JUR-TXG",
        "Taichung City",
        "臺中市",
        "jurisdiction",
        0,
        False,
        6,
        ("bbox", 24.0, 120.45, 24.45, 121.45),
        "TCHPD-DISPATCH",
        [],
        {},
    ),
    (
        "JUR-KHH",
        "Kaohsiung City",
        "高雄市",
        "jurisdiction",
        0,
        False,
        6,
        ("bbox", 22.45, 120.15, 23.47, 121.05),
        "KCPD-DISPATCH",
        [],
        {},
    ),
    (
        "JUR-PEN",
        "Penghu County",
        "澎湖縣",
        "jurisdiction",
        0,
        False,
        6,
        ("bbox", 23.15, 119.3, 23.8, 119.75),
        "PHPD-DISPATCH",
        ["CGA-KINMEN"],
        {},
    ),
    (
        "JUR-KNH",
        "Kinmen County",
        "金門縣",
        "jurisdiction",
        0,
        False,
        6,
        ("bbox", 24.37, 118.19, 24.54, 118.50),
        "KMPD-DISPATCH",
        ["CGA-KINMEN"],
        {},
    ),
    (
        "JUR-LNN",
        "Lienchiang County (Matsu)",
        "連江縣（馬祖）",
        "jurisdiction",
        0,
        False,
        6,
        ("bbox", 25.93, 119.88, 26.40, 120.52),
        "LCPD-DISPATCH",
        ["CGA-KINMEN"],
        {},
    ),
    # Published CAA zones
    (
        "APT-TPE",
        "Taoyuan International Airport",
        "桃園國際機場",
        "airport",
        0,
        True,
        50,
        ("circle", 25.0777, 121.2328, 6000),
        "APB-OPS",
        ["TYPD-DISPATCH", "CAA-UAS"],
        {},
    ),
    (
        "APT-TSA",
        "Taipei Songshan Airport",
        "臺北松山機場",
        "airport",
        0,
        True,
        50,
        ("circle", 25.0694, 121.5525, 4000),
        "APB-OPS",
        ["TCPD-DISPATCH", "CAA-UAS"],
        {},
    ),
    (
        "APT-KHH",
        "Kaohsiung International Airport",
        "高雄國際機場",
        "airport",
        0,
        True,
        50,
        ("circle", 22.5771, 120.3500, 5000),
        "APB-OPS",
        ["KCPD-DISPATCH", "CAA-UAS"],
        {},
    ),
    (
        "RED-PRES",
        "Presidential Office restricted area",
        "總統府周邊禁航區",
        "red",
        0,
        True,
        60,
        ("circle", 25.0400, 121.5119, 1000),
        "TCPD-DISPATCH",
        [],
        {},
    ),
    (
        "YEL-DAAN",
        "Da'an Forest Park (yellow)",
        "大安森林公園限航區",
        "yellow",
        0,
        True,
        20,
        ("circle", 25.0300, 121.5357, 600),
        "TCPD-DISPATCH",
        [],
        {},
    ),
    (
        "RES-XINYI",
        "Xinyi residential (demo)",
        "信義區住宅區（示範）",
        "residential",
        0,
        False,
        15,
        ("circle", 25.0330, 121.5654, 1200),
        "TCPD-DISPATCH",
        [],
        {},
    ),
    (
        "KNH-STRICT",
        "Kinmen restricted areas",
        "金門限航區",
        "outlying_islands_strict",
        0,
        True,
        70,
        ("bbox", 24.37, 118.19, 24.54, 118.50),
        "KMPD-DISPATCH",
        ["CGA-KINMEN", "MND-KINMEN"],
        {"3": 60, "2": 300, "1": 1800},
    ),
    (
        "LNN-STRICT",
        "Matsu restricted areas",
        "馬祖限航區",
        "outlying_islands_strict",
        0,
        True,
        70,
        ("bbox", 25.93, 119.88, 26.40, 120.52),
        "LCPD-DISPATCH",
        ["CGA-KINMEN"],
        {"3": 60, "2": 300, "1": 1800},
    ),
    # Server-only sensitive sites (demo placeholders)
    (
        "MIL-DEMO-HSZ",
        "DEMO military site (Hsinchu)",
        "示範軍事管制區（新竹）",
        "military",
        2,
        False,
        90,
        ("circle", 24.8180, 120.9393, 3000),
        "MND-AIRBASE",
        ["NPA-CMD"],
        {"3": 120},
    ),
    (
        "CI-DEMO-TXG",
        "DEMO critical infrastructure (Taichung coast)",
        "示範關鍵基礎設施（臺中）",
        "critical_infrastructure",
        1,
        False,
        80,
        ("circle", 24.2125, 120.4814, 2000),
        "TCHPD-DISPATCH",
        ["NPA-CMD"],
        {},
    ),
]

L = ("zh-TW", "en", "vi", "id", "th", "fil", "de", "fr")

DE_FR = {
    "authorized_flight": ("Es handelte sich um einen genehmigten Einsatz.", "Il s'agissait d'une activité autorisée."),
    "operator_penalized": (
        "Die verantwortliche Person wurde ermittelt und eine Strafe verhängt.",
        "L'opérateur a été identifié et sanctionné.",
    ),
    "operator_advised": (
        "Die verantwortliche Person wurde ermittelt und belehrt.",
        "L'opérateur a été identifié et averti.",
    ),
    "unable_to_locate": (
        "Wir konnten das Objekt oder die verantwortliche Person nicht finden.",
        "Nous n'avons pas pu localiser l'engin ni son opérateur.",
    ),
    "no_activity_confirmed": (
        "Es konnte keine verdächtige Aktivität bestätigt werden.",
        "Aucune activité suspecte n'a pu être confirmée.",
    ),
    "report_unfounded": (
        "Nach Prüfung hat sich die Meldung als unbegründet erwiesen.",
        "Après examen, ce signalement s'est révélé infondé.",
    ),
    "referred": (
        "Der Fall wurde an eine andere Behörde weitergeleitet.",
        "Ce dossier a été transmis à une autre autorité.",
    ),
    "handled_by_authority": ("Von der zuständigen Behörde bearbeitet.", "Traité par l'autorité compétente."),
    "video_flight_direction": (
        "Wenn das Objekt noch zu sehen ist und es sicher ist, nehmen Sie bitte ein Video auf, das es und seine "
        "Bewegungsrichtung zeigt.",
        "Si l'engin est encore visible et que vous êtes en sécurité, filmez-le ainsi que sa direction de déplacement.",
    ),
    "photo_flight_direction": (
        "Bitte senden Sie ein Foto, das zeigt, in welche Richtung sich das Objekt bewegt hat.",
        "Veuillez envoyer une photo montrant dans quelle direction l'engin se déplaçait.",
    ),
    "photo_wide_landmarks": (
        "Bitte senden Sie ein Weitwinkelfoto, das das Objekt zusammen mit markanten Punkten zeigt.",
        "Veuillez envoyer une photo large montrant l'engin avec des repères visibles à proximité.",
    ),
    "audio_rotor": (
        "Wenn Sie das Objekt noch hören, nehmen Sie bitte das Geräusch auf.",
        "Si vous entendez encore l'engin, veuillez enregistrer son bruit.",
    ),
    "any_other_media": (
        "Wenn Sie weitere Fotos oder Videos gemacht haben, senden Sie diese bitte.",
        "Si vous avez pris d'autres photos ou vidéos, veuillez les envoyer.",
    ),
}


def _t(zh, en, vi, id_, th, fil):
    return dict(zip(L[:6], (zh, en, vi, id_, th, fil), strict=True))


TEMPLATES: list = [
    # code, kind, texts, false_report, requested_kinds, sort
    (
        "authorized_flight",
        "outcome",
        _t(
            "經查為合法核准之飛行。",
            "This was an authorized flight.",
            "Đây là chuyến bay đã được cấp phép.",
            "Ini adalah penerbangan yang sudah mendapat izin.",
            "เป็นการบินที่ได้รับอนุญาต",
            "Ito ay isang awtorisadong paglipad.",
        ),
        False,
        [],
        10,
    ),
    (
        "operator_penalized",
        "outcome",
        _t(
            "已查獲操作人並依法裁處。",
            "The operator was identified and a penalty was issued.",
            "Người điều khiển đã được xác định và bị xử phạt.",
            "Operator telah diidentifikasi dan dikenai sanksi.",
            "ระบุตัวผู้บังคับได้แล้วและได้ดำเนินการลงโทษ",
            "Natukoy ang operator at pinatawan ng parusa.",
        ),
        False,
        [],
        20,
    ),
    (
        "operator_advised",
        "outcome",
        _t(
            "已查獲操作人並予以勸導。",
            "The operator was identified and advised.",
            "Người điều khiển đã được xác định và nhắc nhở.",
            "Operator telah diidentifikasi dan diberi teguran.",
            "ระบุตัวผู้บังคับได้แล้วและได้ตักเตือน",
            "Natukoy ang operator at pinagsabihan.",
        ),
        False,
        [],
        30,
    ),
    (
        "unable_to_locate",
        "outcome",
        _t(
            "經到場查看，未能找到可疑載具或操作人。",
            "We were unable to locate the craft or its operator.",
            "Chúng tôi không tìm thấy phương tiện hoặc người điều khiển.",
            "Kami tidak dapat menemukan wahana atau operatornya.",
            "ไม่พบยานพาหนะหรือผู้บังคับ",
            "Hindi namin natagpuan ang sasakyan o ang operator nito.",
        ),
        False,
        [],
        40,
    ),
    (
        "no_activity_confirmed",
        "outcome",
        _t(
            "未能確認有可疑活動。",
            "No suspicious activity could be confirmed.",
            "Không xác nhận được hoạt động đáng ngờ.",
            "Tidak ada aktivitas mencurigakan yang dapat dipastikan.",
            "ไม่สามารถยืนยันได้ว่ามีกิจกรรมต้องสงสัย",
            "Walang kahina-hinalang aktibidad na nakumpirma.",
        ),
        False,
        [],
        50,
    ),
    (
        "report_unfounded",
        "outcome",
        _t(
            "經查證本件通報與事實不符。",
            "After review, this report was found to be unfounded.",
            "Sau khi xem xét, báo cáo này không có cơ sở.",
            "Setelah ditinjau, laporan ini dinyatakan tidak berdasar.",
            "หลังการตรวจสอบ พบว่ารายงานนี้ไม่มีมูล",
            "Matapos suriin, napag-alamang walang batayan ang ulat na ito.",
        ),
        True,
        [],
        60,
    ),
    (
        "referred",
        "outcome",
        _t(
            "本案已移由其他主管機關處理。",
            "This case was referred to another agency.",
            "Vụ việc đã được chuyển cho cơ quan khác.",
            "Kasus ini telah dirujuk ke instansi lain.",
            "ส่งเรื่องต่อให้หน่วยงานอื่นแล้ว",
            "Ang kasong ito ay ipinasa sa ibang ahensya.",
        ),
        False,
        [],
        70,
    ),
    (
        "handled_by_authority",
        "outcome",
        _t(
            "本案已由相關權責機關處理。",
            "Handled by the relevant authority.",
            "Đã được cơ quan có thẩm quyền xử lý.",
            "Ditangani oleh pihak berwenang terkait.",
            "หน่วยงานที่เกี่ยวข้องได้ดำเนินการแล้ว",
            "Hinawakan ng kinauukulang awtoridad.",
        ),
        False,
        [],
        80,
    ),
    (
        "video_flight_direction",
        "evidence_request",
        _t(
            "若可疑載具仍在視線內且安全，請錄一段影片，拍下它及其移動方向。",
            "If the craft is still in sight and it is safe, please record a video showing it and its direction of travel.",
            "Nếu phương tiện vẫn còn trong tầm nhìn và an toàn, vui lòng quay video cho thấy nó và hướng di chuyển.",
            "Jika wahana masih terlihat dan aman, mohon rekam video yang menunjukkan wahana dan arah geraknya.",
            "หากยังมองเห็นยานพาหนะและปลอดภัย กรุณาถ่ายวิดีโอให้เห็นยานพาหนะและทิศทางการเคลื่อนที่",
            "Kung nakikita pa ang sasakyan at ligtas, pakikuhanan ng video ito at ang direksyon ng paggalaw nito.",
        ),
        False,
        ["video"],
        10,
    ),
    (
        "photo_flight_direction",
        "evidence_request",
        _t(
            "請提供一張可看出可疑載具移動方向的照片。",
            "Please send a photo that shows which way the craft was moving.",
            "Vui lòng gửi ảnh cho thấy hướng di chuyển của phương tiện.",
            "Mohon kirim foto yang menunjukkan arah gerak wahana.",
            "กรุณาส่งรูปที่เห็นทิศทางที่ยานพาหนะเคลื่อนที่ไป",
            "Pakipadala ng larawang nagpapakita kung saan papunta ang sasakyan.",
        ),
        False,
        ["photo"],
        20,
    ),
    (
        "photo_wide_landmarks",
        "evidence_request",
        _t(
            "請提供一張廣角照片，同時拍到可疑載具與附近地標。",
            "Please send a wide photo showing the craft together with nearby landmarks.",
            "Vui lòng gửi ảnh góc rộng có phương tiện và các địa danh gần đó.",
            "Mohon kirim foto lebar yang memperlihatkan wahana beserta penanda di sekitarnya.",
            "กรุณาส่งรูปมุมกว้างที่เห็นยานพาหนะพร้อมสถานที่สำคัญใกล้เคียง",
            "Pakipadala ng malawak na larawan na kita ang sasakyan at mga palatandaan sa paligid.",
        ),
        False,
        ["photo"],
        30,
    ),
    (
        "audio_rotor",
        "evidence_request",
        _t(
            "若仍聽得到可疑載具的聲音，請錄一段聲音。",
            "If you can still hear the craft, please record its sound.",
            "Nếu bạn vẫn còn nghe thấy tiếng phương tiện, vui lòng ghi âm lại.",
            "Jika Anda masih mendengar suara wahana, mohon rekam suaranya.",
            "หากยังได้ยินเสียงยานพาหนะ กรุณาบันทึกเสียง",
            "Kung naririnig mo pa ang sasakyan, pakirekord ang tunog nito.",
        ),
        False,
        ["audio"],
        40,
    ),
    (
        "any_other_media",
        "evidence_request",
        _t(
            "若您還有其他照片或影片，請一併提供。",
            "If you took any other photos or videos, please send them.",
            "Nếu bạn còn ảnh hoặc video khác, vui lòng gửi thêm.",
            "Jika Anda memiliki foto atau video lain, mohon kirimkan.",
            "หากมีรูปหรือวิดีโออื่น กรุณาส่งมาด้วย",
            "Kung may iba ka pang larawan o video, pakipadala.",
        ),
        False,
        ["photo", "video"],
        50,
    ),
]


# --- Maritime (USV / vessels / shore). Rough demo geometry; real polygons come from CGA and MND.
DESKS += [
    ("CGA-OPS", "CGA", "Coast Guard duty command center", "海巡署勤務指揮中心", 1, False, True),
]

ZONES += [
    (
        "SEA-TW",
        "Taiwan territorial sea (demo box)",
        "臺灣領海（示範範圍）",
        "territorial_sea",
        0,
        False,
        8,
        ("bbox", 21.7, 119.25, 25.65, 122.25),
        "CGA-OPS",
        ["NPA-CMD"],
        {},
    ),
    (
        "SEA-KM",
        "Kinmen waters",
        "金門海域",
        "territorial_sea",
        0,
        False,
        9,
        ("bbox", 24.30, 118.10, 24.60, 118.55),
        "CGA-KINMEN",
        ["CGA-OPS"],
        {"3": 60, "2": 300, "1": 1800},
    ),
    (
        "SEA-MZ",
        "Matsu waters",
        "馬祖海域",
        "territorial_sea",
        0,
        False,
        9,
        ("bbox", 25.90, 119.80, 26.45, 120.55),
        "CGA-KINMEN",
        ["CGA-OPS"],
        {"3": 60, "2": 300, "1": 1800},
    ),
    (
        "HBR-KEELUNG",
        "Port of Keelung",
        "基隆港",
        "harbor",
        0,
        True,
        40,
        ("circle", 25.1500, 121.7450, 2500),
        "CGA-OPS",
        ["NTPD-DISPATCH"],
        {},
    ),
    (
        "HBR-KAOHSIUNG",
        "Port of Kaohsiung",
        "高雄港",
        "harbor",
        0,
        True,
        40,
        ("circle", 22.5900, 120.2800, 5000),
        "CGA-OPS",
        ["KCPD-DISPATCH"],
        {},
    ),
    (
        "RW-DEMO-ZUOYING",
        "DEMO restricted waters (Zuoying)",
        "示範限制水域（左營）",
        "restricted_waters",
        2,
        False,
        95,
        ("circle", 22.7000, 120.2550, 3500),
        "MND-JOC",
        ["CGA-OPS"],
        {"3": 120},
    ),
    (
        "CD-DEMO-LIAOLUO",
        "DEMO protected coastline (Liaoluo Bay, Kinmen)",
        "示範海岸防護區（金門料羅灣）",
        "coastal_defense",
        1,
        False,
        85,
        ("circle", 24.4100, 118.4300, 3000),
        "CGA-KINMEN",
        ["MND-KINMEN"],
        {"3": 60, "2": 300, "1": 1800},
    ),
]

# Which craft domains each zone applies to (routing + severity). Unlisted zones apply to every domain.
AIR = ["aerial"]
SEA = ["surface", "subsurface", "shore"]
ZONE_DOMAINS = {
    "APT-TPE": AIR,
    "APT-TSA": AIR,
    "APT-KHH": AIR,
    "RED-PRES": AIR,
    "YEL-DAAN": AIR,
    "RES-XINYI": AIR,
    "JUR-TPE": AIR + ["shore"],
    "JUR-NTPC": AIR + ["shore"],
    "JUR-TYN": AIR + ["shore"],
    "JUR-TXG": AIR + ["shore"],
    "JUR-KHH": AIR + ["shore"],
    "JUR-PEN": AIR + ["shore"],
    "JUR-KNH": AIR + ["shore"],
    "JUR-LNN": AIR + ["shore"],
    "SEA-TW": SEA,
    "SEA-KM": SEA,
    "SEA-MZ": SEA,
    "HBR-KEELUNG": SEA,
    "HBR-KAOHSIUNG": SEA,
    "RW-DEMO-ZUOYING": SEA,
    "CD-DEMO-LIAOLUO": SEA,
}


# German and French for every reporter-facing template.
TEMPLATES = [
    (code, kind, {**texts, "de": DE_FR[code][0], "fr": DE_FR[code][1]}, *rest) for code, kind, texts, *rest in TEMPLATES
]
