"""mysql schema

Revision ID: 0001
Revises:
Create Date: 2026-10-03 14:18:01.330002
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_zh", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agency")),
        sa.UniqueConstraint("code", name=op.f("uq_agency_code")),
    )
    op.create_table(
        "aircraft_track",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("icao24", sa.String(length=6), nullable=False),
        sa.Column("callsign", sa.String(length=8), nullable=True),
        sa.Column("at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("alt_m", sa.Double(), nullable=True),
        sa.Column("ground_speed_mps", sa.Double(), nullable=True),
        sa.Column("track_deg", sa.Double(), nullable=True),
        sa.Column("on_ground", sa.Boolean(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aircraft_track")),
    )
    op.create_index("ix_aircraft_track_at_pos", "aircraft_track", ["at", "lat", "lon"], unique=False)
    op.create_index(op.f("ix_aircraft_track_icao24"), "aircraft_track", ["icao24"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "cctv_camera",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("stream_url", sa.Text(), nullable=True),
        sa.Column("snapshot_url", sa.Text(), nullable=True),
        sa.Column("owner", sa.String(length=200), nullable=True),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cctv_camera")),
    )
    op.create_index("ix_cctv_pos", "cctv_camera", ["lat", "lon"], unique=False)
    op.create_table(
        "counter",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_counter")),
    )
    op.create_table(
        "device_reputation",
        sa.Column("device_hash", sa.VARBINARY(length=32), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("false_reports", sa.Integer(), nullable=False),
        sa.Column("confirmed_reports", sa.Integer(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.PrimaryKeyConstraint("device_hash", name=op.f("pk_device_reputation")),
    )
    op.create_table(
        "feed_client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("key_hash", sa.VARBINARY(length=32), nullable=False),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_used", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_client")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_feed_client_key_hash")),
    )
    op.create_table(
        "informant_token",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("secret_hash", sa.VARBINARY(length=32), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("push_token", sa.Text(), nullable=True),
        sa.Column("push_platform", sa.String(length=16), nullable=True),
        sa.Column("last_seen", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_informant_token")),
    )
    op.create_table(
        "live_event",
        sa.Column("seq", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("desk_ids", sa.JSON(), nullable=False),
        sa.Column("agency_ids", sa.JSON(), nullable=False),
        sa.Column("redacted_desk_ids", sa.JSON(), nullable=False),
        sa.Column("field_user_ids", sa.JSON(), nullable=False),
        sa.Column("min_clearance", sa.SmallInteger(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("redacted_payload", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_live_event")),
    )
    op.create_index(op.f("ix_live_event_at"), "live_event", ["at"], unique=False)
    op.create_table(
        "permit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permit_no", sa.String(length=64), nullable=False),
        sa.Column("serials", sa.JSON(), nullable=False),
        sa.Column("area", sa.JSON(), nullable=False),
        sa.Column("valid_from", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("valid_to", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("max_alt_m", sa.Double(), nullable=True),
        sa.Column("operator_name", sa.String(length=200), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permit")),
        sa.UniqueConstraint("permit_no", name=op.f("uq_permit_permit_no")),
    )
    op.create_table(
        "rate_counter",
        sa.Column("key", sa.VARBINARY(length=40), nullable=False),
        sa.Column("window_start", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", "window_start", name=op.f("pk_rate_counter")),
    )
    op.create_table(
        "registry_entry",
        sa.Column("serial", sa.String(length=64), nullable=False),
        sa.Column("registration_no", sa.String(length=64), nullable=True),
        sa.Column("owner_name", sa.String(length=200), nullable=True),
        sa.Column("owner_ref", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("manufacturer", sa.String(length=200), nullable=True),
        sa.Column("mtow_g", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.PrimaryKeyConstraint("serial", name=op.f("pk_registry_entry")),
    )
    op.create_table(
        "template",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("texts", sa.JSON(), nullable=False),
        sa.Column("counts_as_false_report", sa.Boolean(), nullable=False),
        sa.Column("requested_kinds", sa.JSON(), nullable=False),
        sa.Column("sort", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_template")),
    )
    op.create_table(
        "vessel_track",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_kind", sa.String(length=8), server_default="ais", nullable=False),
        sa.Column("mmsi", sa.String(length=9), nullable=True),
        sa.Column("track_id", sa.String(length=64), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=True),
        sa.Column("role_confidence", sa.String(length=8), nullable=True),
        sa.Column("imo", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("callsign", sa.String(length=16), nullable=True),
        sa.Column("ship_type", sa.SmallInteger(), nullable=True),
        sa.Column("flag", sa.String(length=3), nullable=True),
        sa.Column("length_m", sa.Double(), nullable=True),
        sa.Column("at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("sog_kn", sa.Double(), nullable=True),
        sa.Column("cog_deg", sa.Double(), nullable=True),
        sa.Column("heading_deg", sa.Double(), nullable=True),
        sa.Column("nav_status", sa.SmallInteger(), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vessel_track")),
    )
    op.create_index("ix_vessel_track_at_pos", "vessel_track", ["at", "lat", "lon"], unique=False)
    op.create_index(op.f("ix_vessel_track_mmsi"), "vessel_track", ["mmsi"], unique=False)
    op.create_index(op.f("ix_vessel_track_track_id"), "vessel_track", ["track_id"], unique=False)
    op.create_table(
        "video_feed",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=True),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("bearing_deg", sa.Double(), nullable=True),
        sa.Column("fov_deg", sa.Double(), nullable=True),
        sa.Column("snapshot_url", sa.Text(), nullable=True),
        sa.Column("stream_url", sa.Text(), nullable=True),
        sa.Column("domains", sa.JSON(), nullable=False),
        sa.Column("sample_interval_s", sa.Integer(), nullable=False),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_sampled_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("last_frame_sha256", sa.String(length=64), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_feed")),
    )
    op.create_table(
        "weather_observation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("station_id", sa.String(length=32), nullable=False),
        sa.Column("at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("visibility_m", sa.Double(), nullable=True),
        sa.Column("wind_speed_mps", sa.Double(), nullable=True),
        sa.Column("wind_dir_deg", sa.Double(), nullable=True),
        sa.Column("precip_mm", sa.Double(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_observation")),
    )
    op.create_index(op.f("ix_weather_observation_at"), "weather_observation", ["at"], unique=False)
    op.create_index(op.f("ix_weather_observation_station_id"), "weather_observation", ["station_id"], unique=False)
    op.create_index("ix_weather_pos", "weather_observation", ["lat", "lon"], unique=False)
    op.create_table(
        "desk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_zh", sa.String(length=200), nullable=False),
        sa.Column("clearance", sa.SmallInteger(), nullable=False),
        sa.Column("is_catch_all", sa.Boolean(), nullable=False),
        sa.Column("always_staffed", sa.Boolean(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.ForeignKeyConstraint(["agency_id"], ["agency.id"], name=op.f("fk_desk_agency_id_agency")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_desk")),
        sa.UniqueConstraint("code", name=op.f("uq_desk_code")),
    )
    op.create_table(
        "incident",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("first_seen", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("last_seen", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("est_lat", sa.Double(), nullable=True),
        sa.Column("est_lon", sa.Double(), nullable=True),
        sa.Column("position_source", sa.String(length=24), nullable=True),
        sa.Column("est_error_m", sa.Double(), nullable=True),
        sa.Column("est_altitude_m", sa.Double(), nullable=True),
        sa.Column("track", sa.JSON(), nullable=True),
        sa.Column("operator_lat", sa.Double(), nullable=True),
        sa.Column("operator_lon", sa.Double(), nullable=True),
        sa.Column("auto_severity", sa.SmallInteger(), nullable=False),
        sa.Column("severity_reasons", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("matched_zone_ids", sa.JSON(), nullable=False),
        sa.Column("remote_id_serials", sa.JSON(), nullable=False),
        sa.Column("authorization", sa.String(length=24), nullable=False),
        sa.Column("permit_id", sa.Integer(), nullable=True),
        sa.Column("registry_serial", sa.String(length=64), nullable=True),
        sa.Column("adsb_nearby", sa.JSON(), nullable=False),
        sa.Column("weather", sa.JSON(), nullable=True),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("distinct_informants", sa.Integer(), nullable=False),
        sa.Column("sensor_confirmed", sa.Boolean(), nullable=False),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("craft_domain", sa.String(length=16), server_default="aerial", nullable=False),
        sa.Column("craft_type", sa.String(length=32), nullable=True),
        sa.Column("ai_assessment", sa.JSON(), nullable=True),
        sa.Column("vessel_match", sa.JSON(), nullable=True),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["merged_into_id"], ["incident.id"], name=op.f("fk_incident_merged_into_id_incident")),
        sa.ForeignKeyConstraint(["permit_id"], ["permit.id"], name=op.f("fk_incident_permit_id_permit")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident")),
    )
    op.create_index("ix_incident_active_pos", "incident", ["active", "est_lat", "est_lon"], unique=False)
    op.create_index(op.f("ix_incident_last_seen"), "incident", ["last_seen"], unique=False)
    op.create_table(
        "push_outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("sent_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"], ["informant_token.id"], name=op.f("fk_push_outbox_token_id_informant_token")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_outbox")),
    )
    op.create_table(
        "sensor",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("lat", sa.Double(), nullable=True),
        sa.Column("lon", sa.Double(), nullable=True),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=True),
        sa.Column("last_seen", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(["agency_id"], ["agency.id"], name=op.f("fk_sensor_agency_id_agency")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sensor")),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("failed_logins", sa.SmallInteger(), nullable=False),
        sa.Column("locked_until", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("password_changed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("agency_id", sa.Integer(), nullable=True),
        sa.Column("desk_id", sa.Integer(), nullable=True),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("clearance", sa.SmallInteger(), nullable=False),
        sa.Column("field_unit", sa.Boolean(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("on_duty", sa.Boolean(), nullable=False),
        sa.Column("on_duty_since", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("last_seen", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("last_lat", sa.Double(), nullable=True),
        sa.Column("last_lon", sa.Double(), nullable=True),
        sa.Column("last_position_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.ForeignKeyConstraint(["agency_id"], ["agency.id"], name=op.f("fk_app_user_agency_id_agency")),
        sa.ForeignKeyConstraint(["desk_id"], ["desk.id"], name=op.f("fk_app_user_desk_id_desk")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("username", name=op.f("uq_app_user_username")),
    )
    op.create_table(
        "observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=True),
        sa.Column("client_report_id", sa.Uuid(), nullable=True),
        sa.Column("observed_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("received_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("observer_lat", sa.Double(), nullable=True),
        sa.Column("observer_lon", sa.Double(), nullable=True),
        sa.Column("observer_accuracy_m", sa.Double(), nullable=True),
        sa.Column("drone_lat", sa.Double(), nullable=True),
        sa.Column("drone_lon", sa.Double(), nullable=True),
        sa.Column("operator_lat", sa.Double(), nullable=True),
        sa.Column("operator_lon", sa.Double(), nullable=True),
        sa.Column("bearing_deg", sa.Double(), nullable=True),
        sa.Column("bearing_accuracy_deg", sa.Double(), nullable=True),
        sa.Column("elevation_deg", sa.Double(), nullable=True),
        sa.Column("altitude_m", sa.Double(), nullable=True),
        sa.Column("altitude_source", sa.String(length=24), nullable=True),
        sa.Column("track", sa.JSON(), nullable=True),
        sa.Column("remote_id_serial", sa.String(length=64), nullable=True),
        sa.Column("remote_id", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("spam_score", sa.Double(), nullable=False),
        sa.Column("fidelity", sa.String(length=8), nullable=True),
        sa.Column("attestation", sa.String(length=24), nullable=True),
        sa.Column("device_hash", sa.VARBINARY(length=32), nullable=True),
        sa.Column("network_hash", sa.VARBINARY(length=32), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_lang", sa.String(length=8), nullable=True),
        sa.Column("description_translations", sa.JSON(), nullable=False),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("craft_domain", sa.String(length=16), server_default="aerial", nullable=False),
        sa.Column("craft_type", sa.String(length=32), nullable=True),
        sa.Column("interview", sa.JSON(), nullable=True),
        sa.Column("ai_assessment", sa.JSON(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.String(length=48), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("informant_token_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"], name=op.f("fk_observation_incident_id_incident")),
        sa.ForeignKeyConstraint(
            ["informant_token_id"],
            ["informant_token.id"],
            name=op.f("fk_observation_informant_token_id_informant_token"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation")),
        sa.UniqueConstraint("client_report_id", name=op.f("uq_observation_client_report_id")),
    )
    op.create_index(op.f("ix_observation_device_hash"), "observation", ["device_hash"], unique=False)
    op.create_index(op.f("ix_observation_incident_id"), "observation", ["incident_id"], unique=False)
    op.create_index("ix_observation_obs_pos", "observation", ["observer_lat", "observer_lon"], unique=False)
    op.create_index(op.f("ix_observation_observed_at"), "observation", ["observed_at"], unique=False)
    op.create_index(op.f("ix_observation_remote_id_serial"), "observation", ["remote_id_serial"], unique=False)
    op.create_index(op.f("ix_observation_source_id"), "observation", ["source_id"], unique=False)
    op.create_index(op.f("ix_observation_source_type"), "observation", ["source_type"], unique=False)
    op.create_table(
        "zone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_zh", sa.String(length=200), nullable=False),
        sa.Column("zone_type", sa.String(length=32), nullable=False),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("geometry", sa.JSON(), nullable=False),
        sa.Column("min_lat", sa.Double(), nullable=False),
        sa.Column("min_lon", sa.Double(), nullable=False),
        sa.Column("max_lat", sa.Double(), nullable=False),
        sa.Column("max_lon", sa.Double(), nullable=False),
        sa.Column("primary_desk_id", sa.Integer(), nullable=True),
        sa.Column("backup_chain", sa.JSON(), nullable=False),
        sa.Column("ack_timeouts", sa.JSON(), nullable=False),
        sa.Column("domains", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.ForeignKeyConstraint(["primary_desk_id"], ["desk.id"], name=op.f("fk_zone_primary_desk_id_desk")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone")),
        sa.UniqueConstraint("code", name=op.f("uq_zone_code")),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_number", sa.String(length=24), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("desk_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.SmallInteger(), nullable=False),
        sa.Column("classification", sa.SmallInteger(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("ack_deadline", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("route_index", sa.SmallInteger(), nullable=False),
        sa.Column("route_chain", sa.JSON(), nullable=False),
        sa.Column("read_agency_ids", sa.JSON(), nullable=False),
        sa.Column("redacted_desk_ids", sa.JSON(), nullable=False),
        sa.Column("outcome_code", sa.String(length=48), nullable=True),
        sa.Column("outcome_note", sa.Text(), nullable=True),
        sa.Column("defense_notes_enc", sa.LargeBinary(), nullable=True),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("acked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("resolved_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("closed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(["agency_id"], ["agency.id"], name=op.f("fk_cases_agency_id_agency")),
        sa.ForeignKeyConstraint(["assignee_id"], ["app_user.id"], name=op.f("fk_cases_assignee_id_app_user")),
        sa.ForeignKeyConstraint(["desk_id"], ["desk.id"], name=op.f("fk_cases_desk_id_desk")),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"], name=op.f("fk_cases_incident_id_incident")),
        sa.ForeignKeyConstraint(["merged_into_id"], ["cases.id"], name=op.f("fk_cases_merged_into_id_cases")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("case_number", name=op.f("uq_cases_case_number")),
        sa.UniqueConstraint("incident_id", name=op.f("uq_cases_incident_id")),
    )
    op.create_index("ix_case_state_deadline", "cases", ["state", "ack_deadline"], unique=False)
    op.create_index(op.f("ix_cases_ack_deadline"), "cases", ["ack_deadline"], unique=False)
    op.create_index(op.f("ix_cases_agency_id"), "cases", ["agency_id"], unique=False)
    op.create_index(op.f("ix_cases_desk_id"), "cases", ["desk_id"], unique=False)
    op.create_index(op.f("ix_cases_state"), "cases", ["state"], unique=False)
    op.create_table(
        "staff_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.VARBINARY(length=32), nullable=False),
        sa.Column("client", sa.String(length=32), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("last_used", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], name=op.f("fk_staff_session_user_id_app_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_staff_session_token_hash")),
    )
    op.create_index(op.f("ix_staff_session_user_id"), "staff_session", ["user_id"], unique=False)
    op.create_table(
        "case_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("from_state", sa.String(length=16), nullable=True),
        sa.Column("to_state", sa.String(length=16), nullable=True),
        sa.Column("from_desk_id", sa.Integer(), nullable=True),
        sa.Column("to_desk_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_case_event_case_id_cases")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_event")),
    )
    op.create_index(op.f("ix_case_event_at"), "case_event", ["at"], unique=False)
    op.create_index(op.f("ix_case_event_case_id"), "case_event", ["case_id"], unique=False)
    op.create_table(
        "case_field_assignment",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_case_field_assignment_case_id_cases")),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], name=op.f("fk_case_field_assignment_user_id_app_user")),
        sa.PrimaryKeyConstraint("case_id", "user_id", name=op.f("pk_case_field_assignment")),
    )
    op.create_table(
        "evidence_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("template_code", sa.String(length=48), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("answered_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_evidence_request_case_id_cases")),
        sa.ForeignKeyConstraint(["created_by"], ["app_user.id"], name=op.f("fk_evidence_request_created_by_app_user")),
        sa.ForeignKeyConstraint(
            ["template_code"], ["template.code"], name=op.f("fk_evidence_request_template_code_template")
        ),
        sa.ForeignKeyConstraint(
            ["token_id"], ["informant_token.id"], name=op.f("fk_evidence_request_token_id_informant_token")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_request")),
    )
    op.create_index(op.f("ix_evidence_request_case_id"), "evidence_request", ["case_id"], unique=False)
    op.create_index(op.f("ix_evidence_request_token_id"), "evidence_request", ["token_id"], unique=False)
    op.create_table(
        "informant_case",
        sa.Column("token_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_informant_case_case_id_cases")),
        sa.ForeignKeyConstraint(
            ["token_id"], ["informant_token.id"], name=op.f("fk_informant_case_token_id_informant_token")
        ),
        sa.PrimaryKeyConstraint("token_id", "case_id", name=op.f("pk_informant_case")),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_request_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=True),
        sa.Column("sha256_declared", sa.String(length=64), nullable=False),
        sa.Column("sha256_verified", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("captured_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("uploaded_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("attestation", sa.String(length=24), nullable=True),
        sa.Column("storage_key", sa.String(length=255), nullable=True),
        sa.Column("tus_upload_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_request_id"],
            ["evidence_request.id"],
            name=op.f("fk_evidence_evidence_request_id_evidence_request"),
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["observation.id"], name=op.f("fk_evidence_observation_id_observation")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(op.f("ix_evidence_observation_id"), "evidence", ["observation_id"], unique=False)
    op.create_index(op.f("ix_evidence_sha256_declared"), "evidence", ["sha256_declared"], unique=False)
    op.create_table(
        "ai_job",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("feed_id", sa.String(length=64), nullable=True),
        sa.Column("frame_key", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("not_before", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.Column("started_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("finished_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("model", sa.String(length=96), nullable=True),
        sa.Column("prompt_version", sa.String(length=16), nullable=True),
        sa.Column("latency_s", sa.Double(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), server_default=sa.text("CURRENT_TIMESTAMP(6)"), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], name=op.f("fk_ai_job_evidence_id_evidence")),
        sa.ForeignKeyConstraint(["feed_id"], ["video_feed.id"], name=op.f("fk_ai_job_feed_id_video_feed")),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["observation.id"], name=op.f("fk_ai_job_observation_id_observation")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_job")),
    )
    op.create_index("ix_ai_job_claim", "ai_job", ["status", "priority", "id"], unique=False)
    op.create_index(op.f("ix_ai_job_observation_id"), "ai_job", ["observation_id"], unique=False)
    op.create_index(op.f("ix_ai_job_status"), "ai_job", ["status"], unique=False)
    # ### end Alembic commands ###

    op.execute("INSERT INTO counter (name, value) VALUES ('case_number', 0), ('ai_claim', 0)")

    # case_event and audit_log are append-only: audit trail and source of response-time metrics.
    # Creating triggers needs the TRIGGER privilege (and, with binary logging, log_bin_trust_function_creators
    # or SUPER); if that is missing the schema still works and the application never updates these tables.
    for table in ("case_event", "audit_log"):
        for event in ("UPDATE", "DELETE"):
            try:
                op.execute(
                    f"CREATE TRIGGER {table}_no_{event.lower()} BEFORE {event} ON {table} FOR EACH ROW "
                    f"SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '{table} is append-only'"
                )
            except Exception as e:  # noqa: BLE001
                print(f"WARNING: could not create append-only trigger on {table}: {e}")

    # Analytics tier: plain views (MySQL has no materialized views); local time is Asia/Taipei (UTC+8).
    op.execute("""
        CREATE VIEW v_incident_facts AS
        SELECT i.id AS incident_id, c.id AS case_id, c.case_number, c.agency_id, c.desk_id,
               i.first_seen, i.last_seen,
               HOUR(CONVERT_TZ(i.first_seen, '+00:00', '+08:00')) AS hour_local,
               WEEKDAY(CONVERT_TZ(i.first_seen, '+00:00', '+08:00')) + 1 AS dow_local,
               c.severity, c.classification, c.state, c.outcome_code,
               COALESCE(t.counts_as_false_report, 0) AS false_report,
               i.`authorization` AS auth_status, i.sensor_confirmed, i.remote_id_serials,
               JSON_LENGTH(i.remote_id_serials) > 0 AS has_remote_id,
               i.registry_serial, r.owner_ref, r.owner_name, i.matched_zone_ids, i.est_lat, i.est_lon,
               i.observation_count, i.distinct_informants, i.craft_domain, i.craft_type
        FROM incident i
        JOIN cases c ON c.incident_id = i.id
        LEFT JOIN template t ON t.code = c.outcome_code
        LEFT JOIN registry_entry r ON r.serial = i.registry_serial
        WHERE i.merged_into_id IS NULL AND c.state <> 'merged'
    """)
    op.execute("""
        CREATE VIEW v_case_response AS
        SELECT c.id AS case_id, c.agency_id, c.desk_id, c.severity, c.classification, c.created_at,
               MIN(CASE WHEN e.action = 'acknowledged' THEN e.at END) AS acked_at,
               MIN(CASE WHEN e.action = 'resolved' THEN e.at END) AS resolved_at,
               SUM(e.action = 'rerouted') AS reroutes,
               SUM(e.action = 'transferred') AS transfers
        FROM cases c JOIN case_event e ON e.case_id = c.id
        WHERE c.state <> 'merged'
        GROUP BY c.id, c.agency_id, c.desk_id, c.severity, c.classification, c.created_at
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_case_response")
    op.execute("DROP VIEW IF EXISTS v_incident_facts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_job_status"), table_name="ai_job")
    op.drop_index(op.f("ix_ai_job_observation_id"), table_name="ai_job")
    op.drop_index("ix_ai_job_claim", table_name="ai_job")
    op.drop_table("ai_job")
    op.drop_index(op.f("ix_evidence_sha256_declared"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_observation_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("informant_case")
    op.drop_index(op.f("ix_evidence_request_token_id"), table_name="evidence_request")
    op.drop_index(op.f("ix_evidence_request_case_id"), table_name="evidence_request")
    op.drop_table("evidence_request")
    op.drop_table("case_field_assignment")
    op.drop_index(op.f("ix_case_event_case_id"), table_name="case_event")
    op.drop_index(op.f("ix_case_event_at"), table_name="case_event")
    op.drop_table("case_event")
    op.drop_index(op.f("ix_staff_session_user_id"), table_name="staff_session")
    op.drop_table("staff_session")
    op.drop_index(op.f("ix_cases_state"), table_name="cases")
    op.drop_index(op.f("ix_cases_desk_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_agency_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_ack_deadline"), table_name="cases")
    op.drop_index("ix_case_state_deadline", table_name="cases")
    op.drop_table("cases")
    op.drop_table("zone")
    op.drop_index(op.f("ix_observation_source_type"), table_name="observation")
    op.drop_index(op.f("ix_observation_source_id"), table_name="observation")
    op.drop_index(op.f("ix_observation_remote_id_serial"), table_name="observation")
    op.drop_index(op.f("ix_observation_observed_at"), table_name="observation")
    op.drop_index("ix_observation_obs_pos", table_name="observation")
    op.drop_index(op.f("ix_observation_incident_id"), table_name="observation")
    op.drop_index(op.f("ix_observation_device_hash"), table_name="observation")
    op.drop_table("observation")
    op.drop_table("app_user")
    op.drop_table("sensor")
    op.drop_table("push_outbox")
    op.drop_index(op.f("ix_incident_last_seen"), table_name="incident")
    op.drop_index("ix_incident_active_pos", table_name="incident")
    op.drop_table("incident")
    op.drop_table("desk")
    op.drop_index("ix_weather_pos", table_name="weather_observation")
    op.drop_index(op.f("ix_weather_observation_station_id"), table_name="weather_observation")
    op.drop_index(op.f("ix_weather_observation_at"), table_name="weather_observation")
    op.drop_table("weather_observation")
    op.drop_table("video_feed")
    op.drop_index(op.f("ix_vessel_track_track_id"), table_name="vessel_track")
    op.drop_index(op.f("ix_vessel_track_mmsi"), table_name="vessel_track")
    op.drop_index("ix_vessel_track_at_pos", table_name="vessel_track")
    op.drop_table("vessel_track")
    op.drop_table("template")
    op.drop_table("registry_entry")
    op.drop_table("rate_counter")
    op.drop_table("permit")
    op.drop_index(op.f("ix_live_event_at"), table_name="live_event")
    op.drop_table("live_event")
    op.drop_table("informant_token")
    op.drop_table("feed_client")
    op.drop_table("device_reputation")
    op.drop_table("counter")
    op.drop_index("ix_cctv_pos", table_name="cctv_camera")
    op.drop_table("cctv_camera")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_aircraft_track_icao24"), table_name="aircraft_track")
    op.drop_index("ix_aircraft_track_at_pos", table_name="aircraft_track")
    op.drop_table("aircraft_track")
    op.drop_table("agency")
    # ### end Alembic commands ###
